import sys

from manual_parser import *
from pandas_parser import *


file_path = sys.argv[1]


rows = read_csv_manual(file_path)

rows = convert_types(rows)

manual_summary = calculate_summary(rows)

write_json(

    manual_summary,

    "task_3/output/manual_summary.json"

)



df = read_csv_pandas(file_path)

pandas_summary = calculate_summary_pandas(df)

write_json(

    pandas_summary,

    "task_3/output/pandas_summary.json"

)



with open(

    "task_3/output/comparison_report.md",

    "w"

) as file:



    file.write(

        "# Comparison Report\n\n"

    )


    if manual_summary == pandas_summary:

        file.write(
            "The summaries generated by the manual parser and the pandas parser are identical in nature..\n\n"
        )

        file.write(
            "Both implementations produced identical results for total students, "
            "submission statistics, average score, highest and lowest scorers, "
            "domain-wise averages, and student lists.\n\n"
        )

        file.write(
            "This identicality occurred because both implementations process the same "
            "CSV file, apply the same type conversions, and perform the same "
            "calculations and implement the same functionality.\n"
        )


    else:


        file.write(

            "The summaries do not match.\n"

        )



